ALTER TABLE genres ADD COLUMN created_at TIMESTAMPTZ  NULL DEFAULT now();
ALTER TABLE genres ADD COLUMN updated_at TIMESTAMPTZ  NULL DEFAULT now();
ALTER TABLE genres ADD COLUMN deleted_at TIMESTAMPTZ  NULL DEFAULT now(); 