ALTER TABLE users ADD COLUMN created_at TIMESTAMPTZ  NULL DEFAULT now();
ALTER TABLE users ADD COLUMN updated_at TIMESTAMPTZ  NULL DEFAULT now();
ALTER TABLE users ADD COLUMN deleted_at TIMESTAMPTZ  NULL DEFAULT now(); 