CREATE TABLE IF NOT EXISTS studios (
  id        UUID PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  slug      VARCHAR(255) NOT NULL UNIQUE,
  name      VARCHAR(255) NOT NULL UNIQUE,
  country   VARCHAR(100) NOT NULL,
  site_url  VARCHAR(100) NULL DEFAULT NULL,
  created_at TIMESTAMPTZ  NULL DEFAULT NULL,
  updated_at TIMESTAMPTZ  NULL DEFAULT NULL,
  deleted_at TIMESTAMPTZ  NULL DEFAULT NULL
);