CREATE TABLE IF NOT EXISTS tags (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL UNIQUE,
  created_at    TIMESTAMPTZ NULL DEFAULT NULL,
  updated_at    TIMESTAMPTZ NULL DEFAULT NULL,
  deleted_at    TIMESTAMPTZ NULL DEFAULT NULL
);